services:
  - type: web
    name: clinical-qa-assistant
    runtime: python
    plan: free
    buildCommand: >
      pip install -r backend/requirements.txt &&
      cd frontend && npm install && npm run build &&
      rm -rf ../backend/static && cp -r build ../backend/static
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FAISS_INDEX_DIR
        value: ./faiss_index
      - key: PYTHON_VERSION
        value: 3.12.3